### ISSUE TITLE
Crash when attempting to insert energy containers into weaponry which are not MO batteries

### ISSUE THREAD

**Issue by DBotThePony** [MatterOverdrive/MatterOverdrive-Legacy-Edition#26]
Mekanism Energy Cube:
```
Description: Rendering screen

java.lang.ClassCastException: mekanism.common.integration.forgeenergy.ForgeEnergyItemWrapper cannot be cast to matteroverdrive.items.includes.EnergyContainer
	at matteroverdrive.items.includes.MOItemEnergyContainer.getStorage(MOItemEnergyContainer.java:49)
	at matteroverdrive.items.includes.MOItemEnergyContainer.getMaxDamage(MOItemEnergyContainer.java:55)
	at net.minecraft.item.ItemStack.func_77958_k(ItemStack.java:299)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:66)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:44)
	at matteroverdrive.client.render.weapons.WeaponRenderHandler.getWeaponModel(WeaponRenderHandler.java:133)
	at matteroverdrive.gui.GuiWeaponStation.func_146976_a(GuiWeaponStation.java:138)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at matteroverdrive.gui.MOGuiBase.func_73863_a(MOGuiBase.java:129)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
Energy Cell from Thermal Expansion:

```
Description: Rendering screen

java.lang.ClassCastException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1129)

-- Screen render details --
Details:
	Screen name: matteroverdrive.gui.GuiWeaponStation
	Mouse location: Scaled: (373, 180). Absolute: (1119, 474)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1129)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Muirrum** [comment]
Those appear to be errors related to those specific mods. Have you tried the cubes with other mods?

**Comment by DBotThePony** [comment]
I tried *any* valid power source, all of them crash. ~~Seems like `matteroverdrive.items.includes.EnergyContainer` doesn't implement `net.minecraftforge.energy.IEnergyStorage`.
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/integration/forgeenergy/ForgeEnergyItemWrapper.java#L10
https://github.com/MatterOverdrive/MatterOverdrive/blob/1.12.2/src/main/java/matteroverdrive/items/includes/EnergyContainer.java#L7~~

There - https://github.com/MatterOverdrive/MatterOverdrive/blob/1.12.2/src/main/java/matteroverdrive/items/includes/MOItemEnergyContainer.java#L49
It should cast it into `IEnergyStorage`, not into `EnergyContainer`
