### ISSUE TITLE
Alpha debugging of structures

### ISSUE THREAD

**Issue by DBotThePony** [MatterOverdrive/MatterOverdrive-Legacy-Edition#37]
*please note this should be an all-in-one issue for reporting bugs related to being-fixed buildings, it is better to post any found bug here, which weren't listed before.*
## This is the TODO list for structures and related to structures bugs
- [x] Structures generated on edge of chunks are being half-generated most of the time (issue appeared with async worldgen in 1.10)
![bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-10-58.png)
![bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-19-36.png)
![bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-20-00.png)
![bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-28-44.png)
- [ ] Structures are generated without loot in Tritanium crates (loot tables)
![bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-13-46.png)
- [ ] ...except Crash Report (needs to be moved into loot tables)
![crash land](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-16-15.png)
- [ ] Andoirds stuck in floor on structure generation very frequently
![stuck](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-14_07-17-28.png)
- [ ] Currently, its almost impossible to find structures in overworld (but they do spawn on superflat worlds)
_@TheCodedOne you can edit this list at any time, just put `x` instead of spaces into boxes when you manage to fix issue_

**Comment by DBotThePony** [comment]
*The following issue happens ONLY on dedicated server and known to be an issue with outdated code, and is easy to fix*
Server crashes on world generation:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MatterOverdrive (matteroverdrive)
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at matteroverdrive.entity.monster.EntityRogueAndroid.isBiomeValid(EntityRogueAndroid.java:77)
	at matteroverdrive.entity.monster.EntityRogueAndroid.addInBiome(EntityRogueAndroid.java:63)
	at matteroverdrive.entity.monster.EntityRogueAndroid.addAsBiomeGen(EntityRogueAndroid.java:51)
	at matteroverdrive.init.MatterOverdriveEntities.register(MatterOverdriveEntities.java:72)
	at matteroverdrive.MatterOverdrive.postInit(MatterOverdrive.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:271)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
```

I saw many mods affected by this issue, example:
https://github.com/Greymerk/minecraft-roguelike/issues/127
aaand he fixed this in https://github.com/Greymerk/minecraft-roguelike/commit/42beb4d4f9c9ce592fc0d9b62eb83b800e6e16e9#diff-ac449a7c5985d5bb1a53b8cf6090e972 (could help)

**Comment by Muirrum** [comment]
Not seeing any issues with generation on chunk boundaries.
![2018-02-14_06 28 27](https://user-images.githubusercontent.com/8702646/36202354-80129e64-1151-11e8-815c-95090ef647ab.png)
![2018-02-14_06 29 09](https://user-images.githubusercontent.com/8702646/36202355-8028ef2a-1151-11e8-9b28-1cfdab5d8312.png)
![2018-02-14_06 27 18](https://user-images.githubusercontent.com/8702646/36202356-803ae0c2-1151-11e8-9876-65fb85344fcf.png)

**Comment by adrwa** [comment]
thats because there is no issue with generation on a chunk border, its a client desync, leaving the world and reloading it makes the blocks appear, you can notice this by trying to actually walk into part of the "missing" structure, its actually there and collides

**Comment by DBotThePony** [comment]
^ Confirmed. But i think this needs to be fixed too.

**Comment by adrwa** [comment]
For now building generation is disabled outside of dev env with fbf4dde

**Comment by Muirrum** [comment]
@TheCodedOne Just reloaded my world and everything's fine. I'm working on the loot tables now.

**Comment by Muirrum** [comment]
Also I'm not sure what the issue is with the quests. Can you elaborate @roboderpy ?
